### ISSUE TITLE
Trouble deploying to heroku

### ISSUE THREAD

**Issue by fceruti** [applegrew/django-select2#10]
For some reason I'm not completely sure, when I deploy to Heroku I get random 404 errors. On my dev machine everything works fine. In heroku I'm working with just one instance if thats any help.

Try hitting the following url many times and see the outcome I'm talking about (sometimes it works)
http://www.marketily.com/select2/fields/auto.json?term=santiago&page=1&context=&field_id=0%3A2012-10-27+00%3A31%3A33.956297

This is the code for that field:
    class CityChoices(AutoModelSelect2Field):

```
queryset = City.objects
search_fields = ['name__icontains']

field_id = 'id_city'

def get_results(self, request, term, page, context):

    terms = re.split(' |,',term)
    cities = City.objects
    full_query = None

    for t in terms:
        q = Q(name__icontains=t) | Q(country__name__icontains=t)
        full_query = q if not full_query else full_query & q
    cities = cities.filter(full_query).all()[:10]

    res = [ (city.pk, "%s, %s" % (city.name, city.country.name),) for city in cities ]
    return NO_ERR_RESP, False, res
```

**Comment by roboslone** [comment]
Actually the issue is still relevant. Currently I'm deploying my app on 9 machines with shared redis cache, but only 1 of 9 hosts saves given query.

**Comment by codingjoe** [comment]
@roboslone I'm running multiple production apps on heroku using this package. Into which trouble are you running?

**Comment by roboslone** [comment]
I'm not using Heroku, but my instances run on several hosts under load balancer. When I type something into select widget widget_id is signed and cached on one host. If I try to reload page and type the same thing my requests may be sent to different hosts by load balancer. These other hosts have different widget_id's because it's generated from actual object id on each host. So I get  almost consistent HTTP404 on every request.

**Comment by codingjoe** [comment]
That should not matter. It does use the object id, which of course isn't consistent across multiple machines. But it could use a UUID4 or any random id really. Since the ID is passed to the browser. The browser plays it back to the any server and verifies it's authenticity and uses the key to get everything form the shared memory, Django's cache.

You should get a message with the 404 if I'm not mistaken. It might help to figure out the issue. For now I can just guess that you have no the same secret KEY on all machines, which should also break your sessions or you have you cache misconfigured for this particular use. I'd recommend setting up a separate redis db with sufficient size and the proper eviction policy.

Please let me know if I can help you further.

**Comment by roboslone** [comment]
Here's my setup:
* cache backend for redis cluster I'm using: [gist](https://gist.github.com/roboslone/60e82831106707a01cdbf188357015f0)
* redis is used as default cache (for now, only used by select2 and django sessions):
```python
CACHES = {
    'default': {
        'BACKEND': 'cache.RedisClusterCache',
        'OPTIONS': {'startup_nodes': [...]}
    },
}
```
* application is deployed on 9 hosts, secret key is the same for every host
* django_select2 in forms (BootstrapModelSelect2Widget adds bootstrap theme):
```python
class BootstrapModelSelect2Widget(ModelSelect2Widget):
    def build_attrs(self, extra_attrs=None, **kwargs):
        attrs = super().build_attrs(extra_attrs=extra_attrs, **kwargs)
        attrs.setdefault('data-theme', 'bootstrap')
        return attrs

class StorySelect(BootstrapModelSelect2Widget):
    model = Story
    search_fields = ('name__icontains', )

class EventForm(forms.ModelForm):
    class Meta:
        ...
        widgets = {
            'story': StorySelect(),
            ...
        }
```


Here's what I get:
* select on rendered page:
```html
<select class="django-select2 django-select2-heavy" data-ajax--cache="true" data-ajax--type="GET" data-ajax--url="/select2/fields/auto.json" data-allow-clear="true" data-field_id="MTQwMzU3MTI1MDkyNjMy:1baKdk:kMaBIke1SFmrmE5LGdpF4xm9aoo" data-minimum-input-length="0" data-placeholder="" data-theme="bootstrap" id="id_story" name="story">
```
* if I refresh page in browser and request goes to a different dackent field_id chacnges, for example:
```html
<select class="django-select2 django-select2-heavy" data-ajax--cache="true" data-ajax--type="GET" data-ajax--url="/select2/fields/auto.json" data-allow-clear="true" data-field_id="MTQwNjk3NjY4OTI3MTA0:1baKeq:7kIyYB8S6-Y_ZGYrMNrhOf71UMQ" data-minimum-input-length="0" data-placeholder="" data-theme="bootstrap" id="id_story" name="story">
```

But somehow as I test it right now everything works. I guess something wasn't right on my previous tries... Thanks for your help, @codingjoe. I hope if someone runs into similar issue my feedback could be helpful.

**Comment by codingjoe** [comment]
@roboslone great, good to hear that its working for you.
Regarding the ever changing `field_id`: This is due to the fact that the id is created during rendering, thus always on a different server. With the cache as a persistent storage between all machines, this works. It's not ideal, but it eliminates the need to define a separate endpoint for everything. I guess you could use sessions as a storage as well, that might be something to investigate for a next major release.
