### ISSUE TITLE
field_id not found error

### ISSUE THREAD

**Issue by arminbalalaie** [applegrew/django-select2#103]
I am using django-select2 in one of my projects and I am using AutoHeavySelect2MultipleWidget. everything is fine when I am in development env. But when I move to production env I see this error for every request to auto.json "field_id not found error". I know there is a field_id for every auto widget so it can use the right class for response. But what could be the reason for this error ? I know my code is fine becuase it is working in development. Should anything be enabled for this to work in production ?

Please help me. It's so important,
Thanks.

**Comment by darklow** [comment]
I encountered same bug too. My guess it is related when running select2 in multi-processing mode.
We didn't had these errors on dev mode on single process and as soon as we published to production in multi-process mode with uswgi, these errors occurred randomly because of non thread-safe approach somewhere.

Some docs:
http://django-select2.readthedocs.org/en/latest/get_started.html#enable-select2-multi-process-support-default-false

But we have default settings, which means `GENERATE_RANDOM_SELECT2_ID = False` and we shouldn't need `ENABLE_SELECT2_MULTI_PROCESS_SUPPORT` which involves extra dependencies.

```
Django==1.4.5
Django-Select2==3.2.1
```
Unfortunately can't try newest version because of this bug #73

**Comment by goldan** [comment]
Same bug here.

**Comment by goldan** [comment]
I found a workaround. The bug appeared when I initialized a select2 field, which is inherited from AutoModelSelect2Field, dynamically in __init__ method of a Form, i.e. as an *instance variable*. I changed it so that it's initialized in the Form's class definition, i.e. as an *class variable*, shared by all instances, and the bug disappeared.
More info here: https://docs.python.org/2/tutorial/classes.html#class-and-instance-variables

**Comment by codingjoe** [comment]
@goldan would you mind writing a patch?

**Comment by goldan** [comment]
@codingjoe the workaround does not help much to write a patch :( one would need to dig into select2 source code, I can't do that now, sorry.

**Comment by Nekmo** [comment]
I have the same problem after upgrading from Pypi version.

I had to update select2 by Django 1.8.

**Comment by gasinvein** [comment]
For me this error started to occure after upgrading django-select2 from 4.x to 5.x and django from 1.8 to 1.9.
uwsgi is in multiprocess mode.

**Comment by codingjoe** [comment]
@gasinvein seems to be that you didn't configure a persistent cache across multiple instances. Make sure to use redis, memcached or db cache. It does NOT work without it!

**Comment by gasinvein** [comment]
@codingjoe memcached is used as default cache.

**Comment by codingjoe** [comment]
What's your cache timeout? You might want to consider setting a an extra cache for django-select2, as it is suggested in the documentation.

**Comment by gasinvein** [comment]
Sorry for stupid question, but how do I set timeout for memcached?

**Comment by codingjoe** [comment]
There are no stupid questions. [Here is your answer.](https://docs.djangoproject.com/en/1.9/topics/cache/#cache-arguments)

**Comment by gasinvein** [comment]
Now my cache settings looks like this:
```python
CACHES = {
	'default': {
		'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
		'LOCATION': 'unix:/tmp/memcached.sock',
	},
	'select2': {
		'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
		'LOCATION': 'unix:/tmp/memcached.sock',
		'TIMEOUT': 60 * 60 * 24,
	},
}
SELECT2_CACHE_BACKEND = 'select2'
```
Am I doing it right?

**Comment by codingjoe** [comment]
yes, that's looking good!

**Comment by gasinvein** [comment]
Thank you!
15 Мар 2016 г. 11:04 пользователь "Johannes Hoppe" <notifications@github.com>
написал:

yes, that's looking good!

**Comment by gasinvein** [comment]
Thank you!

**Comment by JayTurnr** [comment]
> @gasinvein seems to be that you didn't configure a persistent cache across multiple instances. Make sure to use redis, memcached or db cache. It does NOT work without it!

This should be covered under Getting Started in the docs, should it not?

**Comment by codingjoe** [comment]
It currently is under [configuration](https://django-select2.readthedocs.io/en/latest/django_select2.html#django_select2.conf.Select2Conf.CACHE_BACKEND), but you make a fair point @JayTurnr this should be mentioned in the getting started guide. 
@JayTurnr would you care to fix it in a PR?

**Comment by JayTurnr** [comment]
@codingjoe Happily, I'll try get that done today.

I had the default Django cache set-up (no config in settings.py) and assumed that would just work. You sample code for Redis worked perfectly.
