### ISSUE TITLE
Regarding further maintenance

### ISSUE THREAD

**Issue by codingjoe** [applegrew/django-select2#144]
Hi @applegrew,
it seems that you currently don't have the time required to maintain this package on your own.
The demand still seems pretty high, for a good reason this package is awesome, especially because django's template engine is so slow.

I'd like you to consider accepting new contributors/maintainers. Tho I do have a lot to do already, I do have the time to review pull-requests on one more package. I'm sure we could find at least 3 more people to contribute to this package.

Let me know when you made up your mind.
Cheers,
joe

**Comment by mostafa-anm** [comment]
@applegrew Yep please consider.

Best,
Mostafa

**Comment by applegrew** [comment]
Oh thanks a lot. Yes I do have shortage of time. I welcome all the help. When I did have time I used to verify all PRs manually by pulling them locally and testing them on the testapp. As my free time shrunk I started merging PRs (2 or 3) without verifying, which caused some regressions I guess. Since then I stopped accepting PRs to prevent further damage.

Whoever is interested in contributing to this project, please mail me your short intro at admin AT applegrew DOT com. A short intro about me - http://www.applegrew.com/#AboutMe

Personally I feel, more than anything else, this project needs to have some good Selenium tests.
