### ISSUE TITLE
Init_options documentation was written with malice

### ISSUE THREAD

**Issue by Nekmo** [applegrew/django-select2#173]
I wear an hour trying to figure out why this is not working*:

    def init_options(self):
        self.options['createSearchChoice'] = 'Your_js_function'

* http://django-select2.readthedocs.org/en/latest/ref_widgets.html#django_select2.widgets.Select2Mixin.init_options

This documentation is a lie. According to that, putting a function in that way should work. In fact, in order for the function to work, you must put it this way:

        def init_options(self):
            self.options['createSearchChoice'] = '*START*Your_js_function*END*'

createSearchChoice should always be a function. In the example, a string is returned.

Sorry, I have the crystal ball in the workshop to read the Select2 documentation.

**Comment by codingjoe** [comment]
What are you trying to do? I don't really get your point?

**Comment by dracos** [comment]
Just to note anyone else using the latest version 4, that this bug is correct. The commit that changed this is 36bac0570f6e1c16d27980f8b06ea8e91b9cefd2 – you can see there that the *documentation* for e.g. HeavySelect2TagWidget changes `JSFunctionInContext('django_select2.createSearchChoice')` to `django_select2.createSearchChoice` but the *code* changes `JSFunctionInContext('django_select2.createSearchChoice')` to `*START*django_select2.createSearchChoice*END*`. You need those START/END in order for the string to not be escaped when passed to the browser, as you can see at https://github.com/applegrew/django-select2/commit/36bac0570f6e1c16d27980f8b06ea8e91b9cefd2#diff-ef58fc8cd3b94144380352baed83bbe5R219

As to what we are trying to do – we have a widget that has server-side auto complete plus allows you to add a new entry if not present (e.g. like what #4 wanted); plus AutoHeavySelect2Mixin's __init__ hard coded data_view but we needed a Django namespace, so we work around that. It worked fine in 4.2.2 but broke when upgraded to 4.3.2 before this was spotted.

**Comment by codingjoe** [comment]
@dracos updating to version 5 took me less than an hour in a 100kloc Django project. I must highly recommend it, for there is no more support for version 4.
