### ISSUE TITLE
What is the purpose of extra_data_from_instance method?

### ISSUE THREAD

**Issue by ramganez** [applegrew/django-select2#195]
"These are passed to JavaScript and can be used for custom rendering."  Its mentioned in  extra_data_from_instance method definition?
how can I use that?

**Comment by codingjoe** [comment]
Removed in v5.

**Comment by rizumu** [comment]
@codingjoe This was a useful feature to me in previous versions. Is there a new way of returning extra data from a selected item or are there plans to add similar functionality back?

The example from here https://github.com/applegrew/django-select2/pull/17 is still valid: https://gist.github.com/stefanfoulis/4276256

Another example from my codebase: A venue may have many stages (where musicians perform) which are defined from a venue form. On the event form a user selects a venue via the select2 widget and by utilizing `extra_data_from_instance` I was able to return the venue specific stage options in the callback. With access to the stage choices in javascript, from an add performer inline I was able to populate its stage field so that the stage choices reflected the currently selected venue. This allowed changing the venue and assigning performers to a stage specific to that venue all within the same form.

I used this feature in other situations, and it was very helpful in reducing the need for multi-part forms for tasks that logically make sense to be part of the same form. Returning extra data was useful in other ways, to show the user more info about the item they have just selected, or for creating links to related objects.

```
class VenueChoicesWidget(ModelSelect2Widget):
    search_fields = ["location__name__icontains", ]
    queryset = Venue.objects.order_by("location__name")

    def extra_data_from_instance(self, obj):
        stages = {}
        for stage in obj.stage_set.all():
            stages[stage.pk] = stage.name
        return {
            "stages": stages,
        }
```

**Comment by codingjoe** [comment]
I'm open to a PR, but I personally don't have a need to spend time on such a feature.
I solid implementation would be appreciated tho.

**Comment by rizumu** [comment]
@codingjoe No problem, though I was surprised to find it removed, because the v5 release notes indicated that although you rewrote the project, the feature remained unchanged from v4. This was a feature that a project of mine depended on, and despite some hurdles, its the last remaining issue for me to deal with to fully switch to v5. 

It is a hobby project and my time is limited, but this was useful and is my last blocker to upgrade, so I will look into adding this back, though a workaround inside of my project with ajax may be simplest. Either way, I'll update here after I've had time to dig deeper, just want to note for others it might not be in the near future. Best!

**Comment by codingjoe** [comment]
@rizumu I don't remember this feature being documented. If so I'm sorry. But it was necessary to rewrite the whole package. All in all the project is in a very good health now.
