### ISSUE TITLE
Work of cache algorithm

### ISSUE THREAD

**Issue by IgorYakovlev** [applegrew/django-select2#243]
Hello. What advantage of cache in django-select2 ? 
I think current cache algorithm is wrong or at least not working as expecting.

For example:

Client opens web page with django-select2 control. HeavyWidgets algorithm cached itself, everytime when it renders on page. Widget cached with object id key (unique key). Here we have several problems:

1. if page loaded 1000 times it create 1000 instances of cached objects. Cache stores an objects that probably may not used and it wasted use ram memory. But you can config timeout of cache so, that cached objects will be in expired state, but here  exist second problem

2. For example, you have cache timeout = 300 sec(it's default value in Django cache ).  If user loads page and page remaining open more then 5 minutes, cache of widget will expire. Then user try enter values in select2 controls, he get 404 error. We can set Timeout = 1 year , but then we have problem number 1

Correct me if i'm wrong.

**Comment by codingjoe** [comment]
So you're saying I shouldn't dedicated my pressures free time to open source because I suck at it?

About the topic a hand:
Yes memory could pile up, but only if you have millions of simultaneously visitors. If so, I must kindly ask you to you're put  a fraction billions in ad revenue towards improving this repository.

Yes, the default timeout might not be enough, that's why this issue is well documented and you are advised to configure a separate cache backend.

A side note: both issues where addressed, assessed and documented during the development. Unless you have a better solution I don't see your point of bringing this up again.

**Comment by IgorYakovlev** [comment]
>So you're saying I shouldn't dedicated my pressures free time to open source because I suck at it?

@codingjoe, no, just a question for clear vision.

For my project solution as pointed in documentation separate cache, set None timeout, and make static cache key for widget.

Thanks for answer.

**Comment by codingjoe** [comment]
None is not needed, the session timeout time should be enough. But only if you can't control the size of you cache db. Should work both pretty well.

**Comment by codingjoe** [comment]
And hey, I know you didn't mean it that bad, but it sounded a little rough

**Comment by IgorYakovlev** [comment]
> And hey, I know you didn't mean it that bad, but it sounded a little rough

@codingjoe, no sense to be rude. Just asked and wanted hear your opinion. Sorry, if so.

> None is not needed, the session timeout time should be enough. But only if you can't control the size of you cache db. Should work both pretty well.

Thanks for advise.
