### ISSUE TITLE
Cacheing of widget raises PicklingError

### ISSUE THREAD

**Issue by darbula** [applegrew/django-select2#261]
In this [line](https://github.com/applegrew/django-select2/blob/master/django_select2/forms.py#L226) in `HeavySelect2Mixin` widget is being cached and pickle function is not able to handle it raising `PicklingError`. Cache backend is django's `LocMemCache`.

**Comment by codingjoe** [comment]
Hi @darbula that is correct not every widget can be pickled. That is why the `ModelWidget` is pickled in a different way.
I can only advice you to ether change how you pickle the class instance or cache only the party you need.
[Instructions on how to change the way an object is serialised can be found here.](https://docs.python.org/3/library/pickle.html#pickling-class-instances)

Please let me know if you should extend the documentation to be more specific about this. Since you are the first one to raise that questions, I have no experience of what guidance people might need.

**Comment by darbula** [comment]
Thanks, this is the only advice needed, to know that pickling of widget class is required to be implemented by user.
