### ISSUE TITLE
No result found with whitespace

### ISSUE THREAD

**Issue by sebastien247** [applegrew/django-select2#272]
I obtain "No result found" with whitespace in my search.

```
    city = forms.ModelChoiceField(
        widget=ModelSelect2Widget(
            attrs={
                'data-placeholder': _(u"Toutes les villes"),
                'data-theme': 'search',
            },
            model=City,
            search_fields=['name__istartswith', 'zip_code__istartswith', ],
        ),
        required=False,
        queryset=City.objects.all(),
    )
```

![capture-25](https://cloud.githubusercontent.com/assets/2801027/14612083/bcc76ff2-0595-11e6-83d3-05478d110338.png)

![capture-26](https://cloud.githubusercontent.com/assets/2801027/14612087/c28d934e-0595-11e6-9eec-e9625dfa30ea.png)

**Comment by codingjoe** [comment]
Hi @sebastien247 that is a good point. That does not work since all words get split by whitespaces. Thus it looks for rows that start with 'le' OR 'poizat'. You should use `icontains`.
But this is a valid problem. I think we should change the default behavior a bit. You shouldn't have to define how to search at all, or in more detail.
I created a new ticket, the behavior will be changed in version 6. #273
