### ISSUE TITLE
Cache real objects

### ISSUE THREAD

**Issue by roboslone** [applegrew/django-select2#288]
Hi!

Right now django-select2 caches Querys instead of real objects:
```
{
    'queryset': [[], <django.db.models.sql.query.Query at 0x7f93ac4c24a8>],
    ...
}
```

What's the point? You still have to query the database, and that should be avoided.
Or am I missing something here?

**Comment by codingjoe** [comment]
Yes, I do have the `Query` in the database, but not the `Queryset`. 
To be honest, it would even work if we would just cache the the query string, except you have multiple databases setup. Therefore I believe this solution to be a bit better.

**Comment by roboslone** [comment]
@codingjoe , I'm confused. How is caching query better then caching database response for that query? This kind of cache doesn't reduce database load.

Isn't it much better to fetch objects from database once and then store them with expiration date? 
For example, if default expiration time is 5 minutes, then for most popular queries database wouldn't be hit for 5 minutes. For high load services this would be very beneficial. 

And if one has data that updates constantly and always needs to be fetched from database, one could set expiration time to -1 (although in this case caching could be avoided alltogether).

On the other hand if one has data, that never updates in database (and therefore never expires), one could set expiration time to 0. At that case well heated cache would replace database.

**Comment by codingjoe** [comment]
@roboslone you are talking about separate issue. First of all, the `Query` is just a SQL statement wrapped in some python code. Thus, the statement does not get executed when it's serialized for the cache.

Regarding cache querysets: You can't not cache entire querysets since you don't know their size. Especially the large once, which this package is build for, will overflow you cache faster than you can say Mississippi. Further more it would make no sense, since the queryset that "is cached" is actually filtered again, depending on the users input. Therefore you would need to execute another query anyways.

Using caches to speed up skip db queries isn't such a good idea anyways. The problem might just be, that you are doing the query wrong or are using the wrong db.
For very large querysets, you'd be wise to create full text index and overwrite the `filter_queryset` method on the model widgets to search the index.
