### ISSUE TITLE
Selects in Inlines are not working

### ISSUE THREAD

**Issue by Arany** [applegrew/django-select2#294]
Steps to Reproduce:
- Have a Select2 in an Inline field
- Add a new line
- Try to open the dropdown

Dropdowns of already existing Inline lines work, but not the ones of new lines.
This also happens to StackedInlines when not the select2-field, but the whole model is used in an Inline.

There seems to be already a Fork that may fix this problem (I only checked the code, didn't test it yet): https://github.com/20tab/django-select2

**Comment by codingjoe** [comment]
@Arany hi there. I must admit I didn't get your questions at first. You are talking about the Django admin right?

I don't feel like adding an admin widget at this point, since I spend a great deal of time, actually getting Select2 into Django itself. In the next version, Django 1.11, Select2 will be build into the admin. See django/django#6385

Of course a backport is possible, but requires a lot of work.

**Comment by codingjoe** [comment]
What do you think?

**Comment by Arany** [comment]
Ah, I have not checked out Django 1.11 yet. Will hope that may fix the issue :-)
I hoped you can check out the fork and see if it fixes that, but I may as well wait for Django 1.11.

**Comment by Arany** [comment]
From what i see what is missing is a javascript event that triggers a select2-init on newly added lines.

**Comment by codingjoe** [comment]
@Arany yes it does, but it's easy to implement yourself. You'd just need to add another media file in a subclass. There really isn't much need to fork the repo. Especially if it's not pushed upstream ;)

I'll check out the code again and see if there is something that makes sense to merge at this point.

**Comment by jonesnc** [comment]
@codingjoe Is [this comment](https://github.com/django/django/pull/6385#issuecomment-274650072) correct? will this not make into django 1.11?

**Comment by codingjoe** [comment]
No will be probably v2.0 :/

**Comment by impala2** [comment]
I keep seeing this issue being brought up, but I still have yet to see a working solution. Just "only needs a few lines of javascript, do it yourself". But from what I see it's not as simple as it seems, since it requires a valid, unique `field_id` data attribute to work. Not to mention the `djangoSelect2()` jQuery function does not expect the element to already be initialized.

Can we have a definitive answer on how to do this in the documentation until it's merged into django? Here's what I have so far.

    // event triggered by django after element is cloned
    $(document).on('formset:added', function(e, row) {
        row.find('.select2').remove(); // remove the auto generated DOM since it needs to be replaced
        row.find('.django-select2').data('field_id', '???').djangoSelect2(); // works, but how to get new field_id???
    });

For now I'll just increase the number of inlines so the add row button doesn't need to be used.

**Comment by msi2** [comment]
I manage to make it work using this [https://gist.github.com/yuchant/d935208978a1fc6e3098](https://gist.github.com/yuchant/d935208978a1fc6e3098)

and with a bit of extra css it works fine

**Comment by Bartvds** [comment]
Spend a few hours trying to get this to work on Django 1.11, left frustrated and reverted everything. 

Can we get a snippet that actually works?

**Comment by Arany** [comment]
I could actually workaround this problem, by adding a custom JS (thx to @msi2):

```js
// static/admin/js/jquery-ui.init.js
function require(library) {
    "use strict";
    switch (library) {
        case 'jquery':
            return django.jQuery;
    }
}

// static/admin/js/select2-inline.js
django.jQuery(function ($) {
    'use strict';

    var select2Options = {
        'width': 'resolve'
    };

    $(document).on('formset:added', function (event, row, prefix) {
        row.find('.select2-container').remove();
        $(row.find('.django-select2')).select2(select2Options);
    });
});
```
```py
// admin/fields.py
from django_select2.forms import HeavySelect2Widget
from django import forms


class Select2ModelWidget(HeavySelect2Widget):
    class Media:
        js = [static('admin/js/admin/jquery.restore.js'), static('admin/js/select2-inline.js')]


class BaseSelectField(forms.fields.ChoiceField):
    def __init__(self, *args, **kwargs):
        self.as_model = kwargs.pop('as_model', False)
        kwargs.setdefault('widget', Select2ModelWidget(self.serializer, self.queryset, data_view=self.data_view))
        super().__init__(*args, **kwargs)
```

**Comment by codingjoe** [comment]
Yes, that is also how I solved it in Django itself. I will close this issue for now. I think this is enough documentation to get going. Eventually this will be merged into Django, so I don't see a point of adding this behavior now.
