### ISSUE TITLE
Heavy Select2 widgets that do not use models store useless cache data

### ISSUE THREAD

**Issue by agronick** [applegrew/django-select2#303]
In my application we use Select2 for things like listing file system entries and non-model based sources. I have lots of cache entries storing data like:

```
{u'url': u'/packaging/select/branch/',
 u'widget': <django_select2.forms.HeavySelect2Widget at 0x7fe4cc1b5210>}

```

As far as I can tell this never gets read from anywhere. It gets written into the cache each time the page is rendered. set_to_cache() is called inside render(). Displaying the widget calls render(). In django-select2 there are no views that will use this data. AutoResponseView is dependent on having a queryset. This data is useless.

Personally, I expected the cache on heavy views to do some kind of validation in a form's clean method. Like having the accepted values limited to ones produced by a widget's view. 

That is probably what these cache entries should be used for. We should be able to generate responses based off the user or their actions, and then when they submit the form, validate that what they send back is valid. Currently a user could open up the developer tools and send back anything and it will be accepted.

**Comment by codingjoe** [comment]
Hi @agronick,

let me try to answer your questions one by one.

#### 1. Caching
Sadly at the point of each widget, we do not have access to the request and therefore not to the session as an alternative to the cache.
Yes each page render call will add a new widget to your key, but at least the once we ship have a very low memory footprint. If you implement your own heavy widget you should be mindful of that.
There is no cleaning happening, because the form doesn't know which value was rendered unless we sneak in more values into the from request. That's ok, the `ClearableFileInput` does that too.
But I don't see a benefit here. It's not said, that the user will actually submit the form.
It's more important to set the cache timeout and eviction policy right.

#### 2. Security
No, someone can not just open a browser and call an endpoint. All field IDs are signed by the server. Therefore one can only access information, the server has granted. If you want to extend you security, you can add a permission or locking check yourself easily.

Besides that, I must ask you to raise security issues only via Email.
