### ISSUE TITLE
dependent_fields don't re-filter then parent field changed

### ISSUE THREAD

**Issue by WhyNotHugo** [applegrew/django-select2#388]
I've two fields: provinces and cities, and the cities field is filtered by province depending on the value of province (using the ` feature`).

This works fine, except that changing the province doesn't reset the city field:

* Select provinceA.
* Select cityA (which belongs to provinceA).
* Select provinceB
* cityA remains selected (although it's no longer listed and actually an invalid selection. The `cities` field should be cleared in this scenario.

**Comment by codingjoe** [comment]
Hi @hobarrera yes you are right, that is a problem.
[We discussed it](https://github.com/applegrew/django-select2/pull/321#pullrequestreview-31704213) during the review of this feature.

I would be very glad if you have a solution for that.

**Comment by hobarrera** [comment]
Huh, looking at the diff for that PR is _a lot_ easier than reading the code itself (since in the diff all the relevant bits stand out).

Here's what I thinking can be do (though my JS is **rusty**):

* Listen for [`select2:select`](http://select2.github.io/examples.html#events) events.
* Find other `select` elements with `select2-dependent-fields` set.
* Filter elements which actually point to this one.
* Set the filtered elements to no-selection (`.val(null).trigger("change")`).

I'm not sure, however, if the last bit can be done via the element itself, or we need a reference to the object returned by `.select2()`.

**Comment by codingjoe** [comment]
My JS isn't the best ether, I would certainly appreciate a pull-request if you have an idea how to fix it :) I can ask some of my team mates to review it.

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
