### ISSUE TITLE
Applicationwide solution

### ISSUE THREAD

**Issue by odwrotnie** [applegrew/django-select2#417]
Is there any way to apply the widget for every select in every model?

**Comment by codingjoe** [comment]
Hi @odwrotnie that is a very good question. Sadly I have to answer it with no.
You could add it add it to the regular `Select2Widget` into every select field.
You would just do something like:
```python
Select.__bases__ = (Select2Mixin,) + Select.__bases__
SelectMultiple.__bases__ = (Select2Mixin,) + SelectMultiple.__bases__
```
If you would do that in your `App.ready` method, it would in fact make all selects to Select2 inputs.
But there are some good reasons why you maybe don't want that.
For FK or M2M relations, you really want to use the `AutoSelectWidget`, because it loads the options via AJAX to prevent all options form being rendered which will slow down your page.
For that to work you also need to define `search_fields` so based on which values you want related objects to be found. That is something that can not be done automatically. Thus making this task impossible.

Does that answer you question?

Cheers
-Joe
