### ISSUE TITLE
ModelSelect2Widget change value of <option>  

### ISSUE THREAD

**Issue by pidzej** [applegrew/django-select2#432]
Hi,
I have ModelSelect2Widget can i make from option like this:
```
<option value="67"> Continental 10R20</option>
```
Get in value text from option

```
<option value="Continental 10R20"> Continental 10R20</option>
```
thx for replay

**Comment by codingjoe** [comment]
Hi @pidzej I believe it not to be impossible, but I don't see how that is a good idea. I would always recommend to use the actual value of the foreign key as the option value.

Anyhow if you want to do it, there is nothing special about select2 about it. You do it the same way you do it in Django, which does depend your version, which is why I can't give you a clean answer. Essentially you have to overwrite how the options are rendered and how request data is cleaned. You form field will require those foreign keys.

In any event, I would highly suggest to make sure whatever you use as a value is unique.

Cheers
-Joe
