### ISSUE TITLE
Removal of __version__ breaks compatibility with djangocms-link

### ISSUE THREAD

**Issue by rhooper** [applegrew/django-select2#452]
Not sure if this is something you'd consider fixing, but using pbr and removing __version__ breaks compatibility with djangocms-link, forcing me to use versions prior to 6.

**Comment by codingjoe** [comment]
Hi @rhooper 

I understand your frustration, but that is why it's a major release. Because we did make breaking changes.
Switching to `pbr` was important. It allows me to make releases quickly (even from my phone). This gives uses that are quick assess to their features and bug fixes once they are merged.
Furthermore I maintain many packages, having a simple way to release, without having to manually increment a number is vital.

That being said, if you have stack trace or can tell me where Django-CMS uses `__version__`, I can submit a patch to fix it 😃 

Best
-Joe

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**
