### ISSUE TITLE
'HeavyModelSelect2ChoiceField' does not seem to exist anymore

### ISSUE THREAD

**Issue by joaobarcia** [applegrew/django-select2#454]
Hi, I have inherited an older Django project which we are now updating. One of the widgets being used calls 'HeavyModelSelect2ChoiceField' but that class doesn't even seem to exist anymore. Which widget should we use instead?

Thank you very much

**Comment by codingjoe** [comment]
Hi @joaobarcia,

You must have dug up a very old project. I am feeling your pain 😩 
We released two new major version since then.
The breaking change was in the version 5 release. You will find an upgrade guide here:
https://github.com/applegrew/django-select2/tree/5.0.0#upgrade-from-version-4

Best
-Johannes

**Comment by joaobarcia** [comment]
@codingjoe Hehe, thanks for the quick reply and even more for understanding our pain :) For the moment I've managed to at least not have an error regarding django-select2 being displayed. Once I'm able to actually get the project running  with all the new packages I'll probably have some more questions. Cheers

**Comment by codingjoe** [comment]
@joaobarcia sure, just let me know if you have any questions :)
