### ISSUE TITLE
filtering ModelSelect2MultipleWidget by field owner [Question]

### ISSUE THREAD

**Issue by steeldimon** [applegrew/django-select2#529]
I have some classes:
```python
class AccountSearchFieldMixin(object):
    search_fields = [
        'login__icontains',
        'password__icontains',
        'phone__icontains',
    ]


class AccountSelect2TagWidget(AccountSearchFieldMixin, ModelSelect2MultipleWidget):
    model = VkAccount
    queryset = VkAccount.objects.exclude(proxy__isnull=True)

    def create_value(self, value):
        self.get_queryset().create(name=value)


class TaskVkInvitationsFriendsSearchForm(forms.ModelForm):
    # country = ModelChoiceField(Countries.objects.all(), empty_label=None, label='Страна')f

    class Meta:
        model = TaskVkInvitationsFriendsSearch
        exclude = ['type', 'date_creation', 'date_update', 'maintask', 'invited_friends']
        widgets = {
            'accounts': AccountSelect2TagWidget,
            'cities': CitiesSelect2TagWidget,
            'scheduler_data': forms.HiddenInput,
            # 'country': CountrySelect2TagWidget
        }
```
I want filtering widget['accounts'] by request.user as account owner (Foreignkey)
Can you explain me, how can i do this?

**Comment by codingjoe** [comment]
Hi @steeldimon,

thanks for reaching out. I hope that I can help you. Let's start with `AccountSearchFieldMixin`. You inherit from `object` which is uncommon in Python 3. Please beware that this package does not support Python 2. With that out of the way, let's get started:

What you want to achieve is not entirely easy. You see, form, fields and widgets in general don't have access to the request (by default). So if you would want to access it in a form, you would need to pass it on manually. That being said, since the options for select2 model widgets are loaded dynamically, there is an option after all, to filter by request.

You will need to create your own customer view for this and override the `AutoResponseView.get_queryset`, seealso: https://github.com/applegrew/django-select2/blob/82859121a6285d212d6d42ec8a9b65cf02ee5991/django_select2/views.py#L50-L57


Here an example:

`views.py`
```python
from django_select2.views import AutoResponseView


class AccountJsonView(AutoResponseView):

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            raise Http404
        return qs.filter(owner=self.request.user)
```

`forms.py`
```python
from django import forms
from django_select2.forms import ModelSelect2Widget


class MyForm(forms.Modelform):
    class Meta:
        widgets = {
            'account':  ModelSelect2Widget(data_view='account_json')
         }
```

`urls.py`
```python
from django.conf.urls import url

from .views import AccountJsonView

urlpatterns = [
    url(r"^fields/account.json$",
        AccountJsonView.as_view(), "account_json"),
]
```
